#395 [refactor] Topic 관련 리팩토링
Mile-Writings/Mile-Server pull request #397
Opened 2024-06-25 13:37 UTC by parkheeddong

## ✒️ 관련 이슈번호
- Closes #395 

## Key Changes 🔑

 TopicService를 TopicRetriever, TopicUpdator, TopicRemover, TopicCreator 로 분리 하여 리팩토링하였습니다!!

## To Reviewers 📢

topicService의 findById 를 topicRetriever로 이동하였는데요, 아래와 같은 고민이 있습니다!

기존에 다른 서비스에서 (postService 등) 에서 topicService의 findById를 호출하고 있었는데요, 이 경우 아래 두가지 방안 중 고민이 됩니다

1.  TopicService에서 TopicRetriever의 findById 호출
즉, topicService에 findById 메서드를 유지하되, topicRetriever의 findById 메서드를 호출한다. -> 이 경우, 다른 서비스에서 findById를 호출할 경우, topicService를 통해 호출한다.

2. TopicRetriever의 findById만 유지
즉, topicService에서 findById 메서드를 삭제하고, topicRetriever의 findById 메서드만 유지한다. -> 이 경우, 다른 서비스에서 findById 를 호출할 경우, topicRetriever를 통해 호출한다.

1번의 장점은 다른 서비스가 모두 topicService를 통해 가도록 단일 진입점을 유지할 수 있고,
topicRetriever를 변경할일이 생겨도 다른 서비스들에 영향을 미치지 않을수 있다.. 는 장점이 있는데요
그리고 순환참조 문제를 완벽히 방지하려면 1번 안이 더 맞지 않나 라는 생각이 드네요

중간 레이어가 하나 있다는 생각에 일단 2번으로 구현을 하였으나, 갈수록 1번이 맞지 않나 라는 생각이 들어서 의견을 여쭤봅니다!

2024-06-25 13:58 UTC, sohyundoh reviewed
작업하느라 고생하셨습니다! 

질문주신 내용에 대해 답변 남겨보자면, 순환참조가 발생하는 상황은 아래와 같습니다.
![image](https://github.com/Mile-Writings/Mile-Server/assets/79795051/eb735411-466b-4df2-b258-529f8f95f323)

그렇기 때문에 저희가 엔드포인트를 담당하는 계층을 만들었습니다. 만일 PostService에서 Topic의 역할을 가져와야하는 일이 생기면 아래와 같이 순환참조가 발생하지 않게 막을 수 있습니다.
![image](https://github.com/Mile-Writings/Mile-Server/assets/79795051/a1eef053-b67e-4d6a-9a26-6ac9b47d1e57)

그런데 질문주신 1번의 경우는 서로 바라보게 되어 순환참조를 예방할 수 없을 것 같다는 생각이 듭니다!

코멘트 확인해주세요!

2024-06-25 13:58 UTC, sohyundoh commented on module-domain/src/main/java/com/mile/topic/service/TopicRemover.java
> +        topicRetriever.authenticateTopicWithUser(topic, user);
P1.
이 부분은 TopicRemover의 역할이 아닌 것 같습니다! TopicService에서 합쳐서 관리해주는게 어떨까요?

2024-06-25 13:58 UTC, sohyundoh commented on module-domain/src/main/java/com/mile/topic/service/TopicRemover.java
> +        checkSingleTopicDeletion(topic);
P2.
이 부분은 TopicRetriever의 역할이 아닐까요?

2024-06-25 13:58 UTC, sohyundoh commented on module-domain/src/main/java/com/mile/topic/service/dto/TopicUpdator.java
P1
해당 클래스 위치 확인해주세요!

2024-06-25 14:33 UTC, parkheeddong commented on module-domain/src/main/java/com/mile/topic/service/TopicRemover.java
> +        topicRetriever.authenticateTopicWithUser(topic, user);
좋습니다 :D

2024-06-25 14:34 UTC, parkheeddong commented on module-domain/src/main/java/com/mile/topic/service/dto/TopicUpdator.java
이런실수를..감사합니다

2024-06-25 14:45 UTC, parkheeddong commented
@sohyundoh 남겨주신 코멘트대로 1번의 경우처럼 하게 되면
 PostService -> PostRetriever -> TopicServce -> TopicRetriever -> PostService 처럼 이러한 플로우로 순환참조가 발생할 수 있겠네요..
그런데 동시에 2번의 경우는 컴포넌트 <-> 컴포넌트 간의 순환 참조가 발생할 수 있지 않나용?? TopicRetriever에서 PostRetriever가 필요하고, PostRetriever에서 TopicRetriever가 필요한 경우에요!

2024-06-25 14:59 UTC, sohyundoh commented
> @sohyundoh 남겨주신 코멘트대로 1번의 경우처럼 하게 되면 PostService -> PostRetriever -> TopicServce -> TopicRetriever -> PostService 처럼 이러한 플로우로 순환참조가 발생할 수 있겠네요.. 그런데 동시에 2번의 경우는 컴포넌트 <-> 컴포넌트 간의 순환 참조가 발생할 수 있지 않나용?? TopicRetriever에서 PostRetriever가 필요하고, PostRetriever에서 TopicRetriever가 필요한 경우에요!

흠.. 만일 다른 클래스의 외부컴포넌트를 참조해야하는 구현이라면 service에서 외부컴포넌트를 참조해 하위 컴포넌트로 전달하게 통일하는게 어떨까요?

2024-06-27 08:03 UTC, parkheeddong commented
오오.. 아주 좋습니다!!!

2024-06-27 23:42 UTC, sohyundoh requested changes

2024-06-27 23:42 UTC, sohyundoh commented on module-domain/src/main/java/com/mile/topic/service/TopicRemover.java
> +@Slf4j
P3 사용하지 않는 라이브러리 지워주세요!

2024-06-28 04:48 UTC, sohyundoh approved these changes
굿 고생하셨습니다 :)

2024-06-28 08:43 UTC, merged